# Generated by Django 4.2.24 on 2025-10-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('HOD', 'Head of Department'), ('FACULTY', 'Faculty')], default=None, max_length=20, null=True),
        ),
    ]
