# Generated by Django 4.2.24 on 2025-10-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='message',
            name='target_role',
            field=models.CharField(blank=True, choices=[('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('HOD', 'Head of Department'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('HOD', 'Head of Department'), ('FACULTY', 'Faculty'), ('STAFF', 'Staff')], default=None, max_length=20, null=True, verbose_name='User Role'),
        ),
    ]
