# Generated by Django 5.2.4 on 2025-09-16 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='target_role',
            field=models.CharField(default='STAFF', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='sender_role',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('HOD', 'Head of Department'), ('STAFF', 'Faculty')], default='VICE_PRINCIPAL', max_length=20),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='target_group',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('STAFF', 'Faculty'), ('BOTH', 'Both HOD and Faculty')], default='BOTH', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('HOD', 'Head of Department'), ('STAFF', 'Faculty')], default='STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='voicemessage',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
        migrations.CreateModel(
            name='ReplyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.voicemessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.contact')),
            ],
        ),
    ]
